// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = NewAsset("conntrack.c", "53232df7714d67646636625276f8e4642e7ae36b87014b0dd38f87be5b386a7e")
