// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = NewAsset("conntrack.c", "8173c9f2d1c296d8527ba630e4193f497af784e0befebb724215b5ca81464437")
