// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = NewAsset("conntrack.c", "7df16318d3966c5743ed5c7823797e3f0efe28be354adbef0f0043f73aaa1836")
