// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var FargateTracer = NewAsset("fargate-tracer.c", "6e9003a2bd747c986372de1397442e115fea327261cdf2227699bb32871fea5d")
