// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = newAsset("http.c", "526dcc17876f6f92e91375cc97a34de21f3fc6c93366f7d25897be607b3a3d6e")
