// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = NewAsset("http.c", "ccc9c440c35d547fee1f0e8b992658ca7696aa7142ea520a9b3209b77b2be828")
