// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = newAsset("http.c", "9b3c56fffc43c961347dc2fcaf7b2956cf90c78dc8fd9dcd141a3a4bfcef829d")
