// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Kafka = NewAsset("kafka.c", "0198735ebb5228b1e5d9524928c51c8e0c49dcb18e243c5118c1fa1b7e5e485a")
