// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Kafka = NewAsset("kafka.c", "99de8a2e364315f8fdc3d0055fbc969150e9cd593c503795d56a864fb095ccb4")
