// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Kafka = NewAsset("kafka.c", "84f94898bf2893441eea5b869d84d5713a065ba7bc3b4b3101d2c226a11b732a")
