// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var OomKill = NewRuntimeAsset("oom-kill.c", "26f5e795de5ece546005d55f26a1f58dcc8b153e55fdf07635cd7f04eef18cff")
