// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = newAsset("runtime-security.c", "4c524fd3714e71994797b876b5351611130c7b81b29e92c4e402c2602e8ea83d")
