// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = newAsset("runtime-security.c", "2cdfacff6f3a3d73e91edfe64de18543f22d0ba182001daa9cfbe234d69e0c1c")
