// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "5c3da70ff8a6d5ed81190704bfdd414163467b61461cf66709792dbddbd28e9b")
