// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var TcpQueueLength = NewRuntimeAsset("tcp-queue-length.c", "582ca9a45ab6ec3c18e23e73ad275c792af1f7492d0ac7895a819b786349b11a")
