// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = NewRuntimeAsset("tracer.c", "b7254f112ce4125641ad21466e021f42da9f8ae1a515d89d1d3e234726b858a4")
