// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = NewRuntimeAsset("tracer.c", "6e1d6607f0ea7b677b1887f472804bb1f797d4115aeca214abe05378c7f9c3b4")
