// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = NewAsset("tracer.c", "1f917b05353723a377a34383dce44c4d0f74a03d288b0f3029675e55b5110846")
