// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -fsigned-char /git/datadog-agent/pkg/network/tracer/connection/fargate/tracer_types.go

package fargate

type Tuple struct {
	Saddr     [16]byte /* in6_addr */
	Daddr     [16]byte /* in6_addr */
	Sport     uint16
	Dport     uint16
	Family    uint8
	Protocol  uint8
	Pad_cgo_0 [2]byte
}
type ConnStats struct {
	Sent_bytes   uint64
	Recv_bytes   uint64
	Timestamp    uint64
	Flags        uint32
	Cookie       uint32
	Sent_packets uint64
	Recv_packets uint64
	Direction    uint8
	Pid          uint32
}
type TCPStats struct {
	Retransmits       uint32
	Rtt               uint32
	Rtt_var           uint32
	State_transitions uint16
	Pad_cgo_0         [2]byte
}
type ConnEvent struct {
	Tup        Tuple
	Conn_stats ConnStats
	Tcp_stats  TCPStats
}

type ConnDirection uint8

const (
	Unknown  ConnDirection = 0x0
	Incoming ConnDirection = 0x1
	Outgoing ConnDirection = 0x2
)
