// +build  linux

// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  serializers

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( EventContextSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventContextSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventContextSerializer *EventContextSerializer

func ( EventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventSerializer *EventSerializer
