// +build  linux

// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  serializers

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( BPFEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BPFEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BPFEventSerializer *BPFEventSerializer

func ( BPFMapSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BPFMapSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BPFMapSerializer *BPFMapSerializer

func ( BPFProgramSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BPFProgramSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BPFProgramSerializer *BPFProgramSerializer

func ( BindEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BindEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BindEventSerializer *BindEventSerializer

func ( CapsetSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CapsetSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CapsetSerializer *CapsetSerializer

func ( ContainerContextSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ContainerContextSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ContainerContextSerializer *ContainerContextSerializer

func ( CredentialsSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CredentialsSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CredentialsSerializer *CredentialsSerializer

func ( DDContextSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DDContextSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DDContextSerializer *DDContextSerializer

func ( DNSEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DNSEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DNSEventSerializer *DNSEventSerializer

func ( DNSQuestionSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DNSQuestionSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DNSQuestionSerializer *DNSQuestionSerializer

func ( EventContextSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventContextSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventContextSerializer *EventContextSerializer

func ( EventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventSerializer *EventSerializer

func ( ExitEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ExitEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ExitEventSerializer *ExitEventSerializer

func ( FileEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FileEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FileEventSerializer *FileEventSerializer

func ( FileSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FileSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FileSerializer *FileSerializer

func ( IPPortFamilySerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* IPPortFamilySerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_IPPortFamilySerializer *IPPortFamilySerializer

func ( IPPortSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* IPPortSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_IPPortSerializer *IPPortSerializer

func ( MMapEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MMapEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MMapEventSerializer *MMapEventSerializer

func ( MProtectEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MProtectEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MProtectEventSerializer *MProtectEventSerializer

func ( ModuleEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ModuleEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ModuleEventSerializer *ModuleEventSerializer

func ( MountEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MountEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MountEventSerializer *MountEventSerializer

func ( NetworkContextSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NetworkContextSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NetworkContextSerializer *NetworkContextSerializer

func ( NetworkDeviceSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NetworkDeviceSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NetworkDeviceSerializer *NetworkDeviceSerializer

func ( PTraceEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PTraceEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PTraceEventSerializer *PTraceEventSerializer

func ( ProcessContextSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ProcessContextSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ProcessContextSerializer *ProcessContextSerializer

func ( ProcessCredentialsSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ProcessCredentialsSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ProcessCredentialsSerializer *ProcessCredentialsSerializer

func ( ProcessSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ProcessSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ProcessSerializer *ProcessSerializer

func ( SELinuxBoolChangeSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SELinuxBoolChangeSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SELinuxBoolChangeSerializer *SELinuxBoolChangeSerializer

func ( SELinuxBoolCommitSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SELinuxBoolCommitSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SELinuxBoolCommitSerializer *SELinuxBoolCommitSerializer

func ( SELinuxEnforceStatusSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SELinuxEnforceStatusSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SELinuxEnforceStatusSerializer *SELinuxEnforceStatusSerializer

func ( SELinuxEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SELinuxEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SELinuxEventSerializer *SELinuxEventSerializer

func ( SetgidSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SetgidSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SetgidSerializer *SetgidSerializer

func ( SetuidSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SetuidSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SetuidSerializer *SetuidSerializer

func ( SignalEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SignalEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SignalEventSerializer *SignalEventSerializer

func ( SpliceEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SpliceEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SpliceEventSerializer *SpliceEventSerializer

func ( UserContextSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UserContextSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UserContextSerializer *UserContextSerializer
