// +build  linux

// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  probe

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AbnormalEvent ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AbnormalEvent ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AbnormalEvent *AbnormalEvent

func ( EventLostRead ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventLostRead ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventLostRead *EventLostRead

func ( EventLostWrite ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventLostWrite ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventLostWrite *EventLostWrite
