// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  rules

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PolicyState ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PolicyState ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PolicyState *PolicyState

func ( RuleState ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RuleState ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RuleState *RuleState

func ( RulesetLoadedEvent ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RulesetLoadedEvent ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RulesetLoadedEvent *RulesetLoadedEvent
